[package]
name = "lojidoc"
version = "0.1.0"
licence = "Apache-2.0"
description = "A tool for generating markown documentation for java projects."
authors = ["josh <jobrud314@gmail.com>"]

[dependencies]
regex = "0.1.41"
threadpool = "1.7.1"
lazy_static = "1.0.1"
clap = "2.32"
